language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
services:
  - elasticsearch
install:
  - travis_retry pip install -e .
  - travis_retry pip install file://$(pwd)#egg=djes[dev]
script:
  - py.test --cov djes --cov-report term-missing
after_success:
  - coveralls
sudo: false
